#!/bin/bash

# checks if spotify is current playing
# and returns the name of artist and
# current playing song

songs () {
    func_result=$( spotify-now -e "closed" -p "paused" -i "\uf9c6 %artist - %title" )

    if [[ $func_result == "paused" ]]; then
        ans=$( spotify-now -i "%artist - %title" )
        if [[ ${#ans} -gt 44 ]]; then
            echo -e "\uf8e4  "${ans:0:44}"..."
        else
            echo -e "\uf8e4  "$ans
        fi
    elif [[ $func_result == "closed" ]]; then
        echo -e "\uf9c6 Not Playing"
    else
        if [[ ${#func_result} -gt 50 ]]; then
            echo -e ${func_result:0:50}"..."
        else
            echo -e $func_result
        fi
    fi
}

# checks for current ip
check_ip () {
    echo $(echo -e "\uf1eb " && /sbin/ifconfig wlp3s0 | grep -m 1 inet | awk '{ print $2 }')
}

# check the number of deb packages installed
deb_pacakges () {
    echo -e "\uf8d3 $(dpkg -l | awk '{ print $2 }' | sed 1,6d | wc -l)"
}

# checks for remaining space in /home directory
home_space () {
    echo $(echo -e "\uf7c9" && df -h | grep /dev/sda1 | awk '{ print $1 " " $4 }')
}

# checks how many packages to update
check_updates_apt () {
    echo $(echo -e "\uf8d3" && aptitude search '~U' | wc -l)
}

battery_life () {
    echo $(echo -e "\uf583" && acpi -b | awk '{ split($5,a,":"); print substr($3,0,2), $4, "["a[1]":"a[2]"]" }' | tr -d ',')
}

function get_volume {
    amixer -c 1 get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer -c 1 get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function volume {
    if is_mute ; then
        echo -e "\ufa80 Mute"
    else
        echo -e "\ufa7d $(get_volume)%"
    fi
}


function brightness {
    echo -e "\uf5dd  $(xbacklight | awk '{ print int($1) }')"    
}

xsetroot -name "| `home_space` | `battery_life` | `brightness` | `volume` | `echo -e "\uf455 "` `date +"%a, %d %B %Y, %H:%M"` | `echo -e "\uf306 "` `whoami`@`hostname` "
